REVOKE EXECUTE ON FUNCTION public.are_connected(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.bump_conversation_activity() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_post_counter() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_tag_counter() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_comment_counts() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_post_tag_uses() FROM anon, authenticated;