import { detectGaps } from "@/orb-core/gaps";
import { decideImpulse } from "@/orb-core/impulse";
import { decideCuriosity } from "@/orb-core/curiosity";
import { topicsOf } from "@/orb-core/memory";
const nodes = JSON.parse(await Bun.file("/tmp/orbsim/nodes.json").text());
const conns = JSON.parse(await Bun.file("/tmp/orbsim/conns.json").text());
const msgs = JSON.parse(await Bun.file("/tmp/orbsim/msgs.json").text());
const now = Date.now();
const gapNodes = nodes.map((r:any)=>({id:r.id,content:r.content,topic:r.topic,importance:r.importance,confidence:r.confidence,longTermValue:r.long_term_value,temporalScope:r.temporal_scope,category:r.category,activationCount:r.activation_count,lastAccessedAt:new Date(r.last_accessed_at).getTime()}));
const conversationTopics = msgs.flatMap((m:any)=>topicsOf(m.body));
const detected = detectGaps({nodes:gapNodes, connections:conns.map((c:any)=>({sourceNodeId:c.source_node_id,targetNodeId:c.target_node_id,weight:c.weight})), conversationTopics, now});
console.log("topics", conversationTopics);
console.log("detected", detected.map(g=>({type:g.type,topic:g.topic,imp:g.importance,conf:g.confidence,fr:g.futureRelevance,exp:new Date(g.expiresAt).toISOString(),q:g.suggestedQuestion.slice(0,60)})));
const prev = ["Worauf bezieht sich „Nicht faktisch falsch“?","Warum hast du dich bei deinem Gaming-PC für die Nvidia RTX 5070 entschieden?","Welche konkrete persönliche Information über dich soll ich mir merken?"];
const dec = decideImpulse({gaps:detected,curiosity:0.9925,conversationTopics,recentUserTexts:msgs.filter((m:any)=>m.role==="user").map((m:any)=>m.body),previousImpulses:prev,knownAnswers:nodes.map((n:any)=>n.content),openQuestion:false,lastImpulseAt:new Date("2026-09-20T07:26:11.726Z").getTime(),now});
console.log("IMPULSE", dec.action, dec.reason, "suppressed", dec.suppressed, "candidates", dec.candidates.map(c=>({p:c.priority,s:c.score,t:c.gap.type})));
console.log("CURIOSITY energy0:", decideCuriosity({curiosity:0.9925,energy:0,gaps:[],lastQuestionAt:new Date("2026-09-20T07:26:11.726Z").getTime(),openQuestion:false,now}));
