ALTER POLICY "account_security_events_select" ON public.account_security_events USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "account_security_events_admin_select" ON public.account_security_events USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "ad_campaigns_select_admin" ON public.ad_campaigns USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "ad_test_events_select_admin" ON public.ad_test_events USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "admin_audit_log_select_admin" ON public.admin_audit_log USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "admins manage categories" ON public.channel_categories USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "admins update channels" ON public.channels USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "admins read all channels" ON public.channels USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "content_moderation_log_admin_select" ON public.content_moderation_log USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "counter_events admin read" ON public.counter_events USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "easter_eggs_admin_write" ON public.easter_eggs USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "Admins read all feedback" ON public.feedback USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "categories managed by admins" ON public.interest_categories USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "ops_events_admin_select" ON public.ops_events USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "ops_incidents_admin_select" ON public.ops_incidents USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "Admins can read moderation jobs" ON public.post_moderation_jobs USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "reports_select_admin" ON public.reports USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "slang_tag_moderation_events_select_admin" ON public.slang_tag_moderation_events USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "slang_tags_delete_admin" ON public.slang_tags USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "user_bans_select_admin" ON public.user_bans USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));
ALTER POLICY "user_warnings_select_admin" ON public.user_warnings USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::app_role)));