/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestusersRouteImport } from './routes/admin.testusers'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminSlangtagsRouteImport } from './routes/admin.slangtags'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPausesRouteImport } from './routes/admin.pauses'
import { Route as AdminLogRouteImport } from './routes/admin.log'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminActiveRouteImport } from './routes/admin.active'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedSlangtagNameRouteImport } from './routes/_authenticated/slangtag.$name'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestusersRoute = AdminTestusersRouteImport.update({
  id: '/testusers',
  path: '/testusers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlangtagsRoute = AdminSlangtagsRouteImport.update({
  id: '/slangtags',
  path: '/slangtags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPausesRoute = AdminPausesRouteImport.update({
  id: '/pauses',
  path: '/pauses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActiveRoute = AdminActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlangtagNameRoute =
  AuthenticatedSlangtagNameRouteImport.update({
    id: '/slangtag/$name',
    path: '/slangtag/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/dev': typeof AuthenticatedDevRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/admin/active': typeof AdminActiveRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/pauses': typeof AdminPausesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slangtags': typeof AdminSlangtagsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/testusers': typeof AdminTestusersRoute
  '/admin/users': typeof AdminUsersRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/slangtag/$name': typeof AuthenticatedSlangtagNameRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/dev': typeof AuthenticatedDevRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/admin/active': typeof AdminActiveRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/pauses': typeof AdminPausesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slangtags': typeof AdminSlangtagsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/testusers': typeof AdminTestusersRoute
  '/admin/users': typeof AdminUsersRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin': typeof AdminIndexRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/slangtag/$name': typeof AuthenticatedSlangtagNameRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/_authenticated/dev': typeof AuthenticatedDevRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/admin/active': typeof AdminActiveRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/pauses': typeof AdminPausesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slangtags': typeof AdminSlangtagsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/testusers': typeof AdminTestusersRoute
  '/admin/users': typeof AdminUsersRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/slangtag/$name': typeof AuthenticatedSlangtagNameRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/dev'
    | '/posts'
    | '/admin/active'
    | '/admin/ads'
    | '/admin/comments'
    | '/admin/log'
    | '/admin/pauses'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/slangtags'
    | '/admin/stats'
    | '/admin/testusers'
    | '/admin/users'
    | '/newsletter/confirm'
    | '/post/$postId'
    | '/admin/'
    | '/profile/$username'
    | '/slangtag/$name'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/dev'
    | '/posts'
    | '/admin/active'
    | '/admin/ads'
    | '/admin/comments'
    | '/admin/log'
    | '/admin/pauses'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/slangtags'
    | '/admin/stats'
    | '/admin/testusers'
    | '/admin/users'
    | '/newsletter/confirm'
    | '/post/$postId'
    | '/admin'
    | '/profile/$username'
    | '/slangtag/$name'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/_authenticated/dev'
    | '/_authenticated/posts'
    | '/admin/active'
    | '/admin/ads'
    | '/admin/comments'
    | '/admin/log'
    | '/admin/pauses'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/slangtags'
    | '/admin/stats'
    | '/admin/testusers'
    | '/admin/users'
    | '/newsletter/confirm'
    | '/post/$postId'
    | '/admin/'
    | '/_authenticated/profile/$username'
    | '/_authenticated/slangtag/$name'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  PostPostIdRoute: typeof PostPostIdRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testusers': {
      id: '/admin/testusers'
      path: '/testusers'
      fullPath: '/admin/testusers'
      preLoaderRoute: typeof AdminTestusersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slangtags': {
      id: '/admin/slangtags'
      path: '/slangtags'
      fullPath: '/admin/slangtags'
      preLoaderRoute: typeof AdminSlangtagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pauses': {
      id: '/admin/pauses'
      path: '/pauses'
      fullPath: '/admin/pauses'
      preLoaderRoute: typeof AdminPausesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/active': {
      id: '/admin/active'
      path: '/active'
      fullPath: '/admin/active'
      preLoaderRoute: typeof AdminActiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slangtag/$name': {
      id: '/_authenticated/slangtag/$name'
      path: '/slangtag/$name'
      fullPath: '/slangtag/$name'
      preLoaderRoute: typeof AuthenticatedSlangtagNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDevRoute: typeof AuthenticatedDevRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedSlangtagNameRoute: typeof AuthenticatedSlangtagNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDevRoute: AuthenticatedDevRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedSlangtagNameRoute: AuthenticatedSlangtagNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminActiveRoute: typeof AdminActiveRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminLogRoute: typeof AdminLogRoute
  AdminPausesRoute: typeof AdminPausesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSlangtagsRoute: typeof AdminSlangtagsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminTestusersRoute: typeof AdminTestusersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActiveRoute: AdminActiveRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminLogRoute: AdminLogRoute,
  AdminPausesRoute: AdminPausesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSlangtagsRoute: AdminSlangtagsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminTestusersRoute: AdminTestusersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  PostPostIdRoute: PostPostIdRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
