/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareTargetRouteImport } from './routes/share-target'
import { Route as RichtlinienRouteImport } from './routes/richtlinien'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestDataRouteImport } from './routes/request-data'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as DemoMessengerRouteImport } from './routes/demo.messenger'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUsernamesRouteImport } from './routes/admin.usernames'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminSlangtagsRouteImport } from './routes/admin.slangtags'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPausesRouteImport } from './routes/admin.pauses'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLogRouteImport } from './routes/admin.log'
import { Route as AdminLivetestRouteImport } from './routes/admin.livetest'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminBetaRouteImport } from './routes/admin.beta'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminActiveRouteImport } from './routes/admin.active'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedGlobeRouteImport } from './routes/_authenticated/globe'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels.index'
import { Route as ApiPublicRetentionRunRouteImport } from './routes/api/public/retention-run'
import { Route as ApiPublicPushRunRouteImport } from './routes/api/public/push-run'
import { Route as ApiPublicModerationRunRouteImport } from './routes/api/public/moderation-run'
import { Route as ApiPublicCountersRunRouteImport } from './routes/api/public/counters-run'
import { Route as ApiPublicCacheMetricsRouteImport } from './routes/api/public/cache-metrics'
import { Route as ApiPublicBetaLaunchRunRouteImport } from './routes/api/public/beta-launch-run'
import { Route as AuthenticatedSlangtagNameRouteImport } from './routes/_authenticated/slangtag.$name'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedPPostIdRouteImport } from './routes/_authenticated/p.$postId'
import { Route as AuthenticatedHashtagNameRouteImport } from './routes/_authenticated/hashtag.$name'
import { Route as AuthenticatedChannelsChannelIdRouteImport } from './routes/_authenticated/channels.$channelId'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const ShareTargetRoute = ShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => rootRouteImport,
} as any)
const RichtlinienRoute = RichtlinienRouteImport.update({
  id: '/richtlinien',
  path: '/richtlinien',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDataRoute = RequestDataRouteImport.update({
  id: '/request-data',
  path: '/request-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMessengerRoute = DemoMessengerRouteImport.update({
  id: '/demo/messenger',
  path: '/demo/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsernamesRoute = AdminUsernamesRouteImport.update({
  id: '/usernames',
  path: '/usernames',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlangtagsRoute = AdminSlangtagsRouteImport.update({
  id: '/slangtags',
  path: '/slangtags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPausesRoute = AdminPausesRouteImport.update({
  id: '/pauses',
  path: '/pauses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLivetestRoute = AdminLivetestRouteImport.update({
  id: '/livetest',
  path: '/livetest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBetaRoute = AdminBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActiveRoute = AdminActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGlobeRoute = AuthenticatedGlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRetentionRunRoute = ApiPublicRetentionRunRouteImport.update({
  id: '/api/public/retention-run',
  path: '/api/public/retention-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushRunRoute = ApiPublicPushRunRouteImport.update({
  id: '/api/public/push-run',
  path: '/api/public/push-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicModerationRunRoute = ApiPublicModerationRunRouteImport.update({
  id: '/api/public/moderation-run',
  path: '/api/public/moderation-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCountersRunRoute = ApiPublicCountersRunRouteImport.update({
  id: '/api/public/counters-run',
  path: '/api/public/counters-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCacheMetricsRoute = ApiPublicCacheMetricsRouteImport.update({
  id: '/api/public/cache-metrics',
  path: '/api/public/cache-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBetaLaunchRunRoute = ApiPublicBetaLaunchRunRouteImport.update({
  id: '/api/public/beta-launch-run',
  path: '/api/public/beta-launch-run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlangtagNameRoute =
  AuthenticatedSlangtagNameRouteImport.update({
    id: '/slangtag/$name',
    path: '/slangtag/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPPostIdRoute = AuthenticatedPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHashtagNameRoute =
  AuthenticatedHashtagNameRouteImport.update({
    id: '/hashtag/$name',
    path: '/hashtag/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChannelsChannelIdRoute =
  AuthenticatedChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/delete-account': typeof DeleteAccountRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/impressum': typeof ImpressumRoute
  '/request-data': typeof RequestDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/richtlinien': typeof RichtlinienRoute
  '/share-target': typeof ShareTargetRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/dev': typeof AuthenticatedDevRoute
  '/globe': typeof AuthenticatedGlobeRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/admin/active': typeof AdminActiveRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/livetest': typeof AdminLivetestRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/pauses': typeof AdminPausesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slangtags': typeof AdminSlangtagsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/usernames': typeof AdminUsernamesRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/messenger': typeof DemoMessengerRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
  '/hashtag/$name': typeof AuthenticatedHashtagNameRoute
  '/p/$postId': typeof AuthenticatedPPostIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/slangtag/$name': typeof AuthenticatedSlangtagNameRoute
  '/api/public/beta-launch-run': typeof ApiPublicBetaLaunchRunRoute
  '/api/public/cache-metrics': typeof ApiPublicCacheMetricsRoute
  '/api/public/counters-run': typeof ApiPublicCountersRunRoute
  '/api/public/moderation-run': typeof ApiPublicModerationRunRoute
  '/api/public/push-run': typeof ApiPublicPushRunRoute
  '/api/public/retention-run': typeof ApiPublicRetentionRunRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/delete-account': typeof DeleteAccountRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/impressum': typeof ImpressumRoute
  '/request-data': typeof RequestDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/richtlinien': typeof RichtlinienRoute
  '/share-target': typeof ShareTargetRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/dev': typeof AuthenticatedDevRoute
  '/globe': typeof AuthenticatedGlobeRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/admin/active': typeof AdminActiveRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/livetest': typeof AdminLivetestRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/pauses': typeof AdminPausesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slangtags': typeof AdminSlangtagsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/usernames': typeof AdminUsernamesRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/messenger': typeof DemoMessengerRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin': typeof AdminIndexRoute
  '/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
  '/hashtag/$name': typeof AuthenticatedHashtagNameRoute
  '/p/$postId': typeof AuthenticatedPPostIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/slangtag/$name': typeof AuthenticatedSlangtagNameRoute
  '/api/public/beta-launch-run': typeof ApiPublicBetaLaunchRunRoute
  '/api/public/cache-metrics': typeof ApiPublicCacheMetricsRoute
  '/api/public/counters-run': typeof ApiPublicCountersRunRoute
  '/api/public/moderation-run': typeof ApiPublicModerationRunRoute
  '/api/public/push-run': typeof ApiPublicPushRunRoute
  '/api/public/retention-run': typeof ApiPublicRetentionRunRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/delete-account': typeof DeleteAccountRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/impressum': typeof ImpressumRoute
  '/request-data': typeof RequestDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/richtlinien': typeof RichtlinienRoute
  '/share-target': typeof ShareTargetRoute
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRoute
  '/_authenticated/dev': typeof AuthenticatedDevRoute
  '/_authenticated/globe': typeof AuthenticatedGlobeRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/admin/active': typeof AdminActiveRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/livetest': typeof AdminLivetestRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/pauses': typeof AdminPausesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slangtags': typeof AdminSlangtagsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/usernames': typeof AdminUsernamesRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/messenger': typeof DemoMessengerRoute
  '/post/$postId': typeof PostPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
  '/_authenticated/hashtag/$name': typeof AuthenticatedHashtagNameRoute
  '/_authenticated/p/$postId': typeof AuthenticatedPPostIdRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/slangtag/$name': typeof AuthenticatedSlangtagNameRoute
  '/api/public/beta-launch-run': typeof ApiPublicBetaLaunchRunRoute
  '/api/public/cache-metrics': typeof ApiPublicCacheMetricsRoute
  '/api/public/counters-run': typeof ApiPublicCountersRunRoute
  '/api/public/moderation-run': typeof ApiPublicModerationRunRoute
  '/api/public/push-run': typeof ApiPublicPushRunRoute
  '/api/public/retention-run': typeof ApiPublicRetentionRunRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agb'
    | '/auth'
    | '/datenschutz'
    | '/delete-account'
    | '/favicon.ico'
    | '/impressum'
    | '/request-data'
    | '/reset-password'
    | '/richtlinien'
    | '/share-target'
    | '/arena'
    | '/creator'
    | '/dev'
    | '/globe'
    | '/posts'
    | '/admin/active'
    | '/admin/ads'
    | '/admin/beta'
    | '/admin/comments'
    | '/admin/feedback'
    | '/admin/livetest'
    | '/admin/log'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/pauses'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/slangtags'
    | '/admin/stats'
    | '/admin/usernames'
    | '/admin/users'
    | '/demo/messenger'
    | '/post/$postId'
    | '/admin/'
    | '/channels/$channelId'
    | '/hashtag/$name'
    | '/p/$postId'
    | '/profile/$username'
    | '/slangtag/$name'
    | '/api/public/beta-launch-run'
    | '/api/public/cache-metrics'
    | '/api/public/counters-run'
    | '/api/public/moderation-run'
    | '/api/public/push-run'
    | '/api/public/retention-run'
    | '/channels/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/auth'
    | '/datenschutz'
    | '/delete-account'
    | '/favicon.ico'
    | '/impressum'
    | '/request-data'
    | '/reset-password'
    | '/richtlinien'
    | '/share-target'
    | '/arena'
    | '/creator'
    | '/dev'
    | '/globe'
    | '/posts'
    | '/admin/active'
    | '/admin/ads'
    | '/admin/beta'
    | '/admin/comments'
    | '/admin/feedback'
    | '/admin/livetest'
    | '/admin/log'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/pauses'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/slangtags'
    | '/admin/stats'
    | '/admin/usernames'
    | '/admin/users'
    | '/demo/messenger'
    | '/post/$postId'
    | '/admin'
    | '/channels/$channelId'
    | '/hashtag/$name'
    | '/p/$postId'
    | '/profile/$username'
    | '/slangtag/$name'
    | '/api/public/beta-launch-run'
    | '/api/public/cache-metrics'
    | '/api/public/counters-run'
    | '/api/public/moderation-run'
    | '/api/public/push-run'
    | '/api/public/retention-run'
    | '/channels'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/agb'
    | '/auth'
    | '/datenschutz'
    | '/delete-account'
    | '/favicon.ico'
    | '/impressum'
    | '/request-data'
    | '/reset-password'
    | '/richtlinien'
    | '/share-target'
    | '/_authenticated/arena'
    | '/_authenticated/creator'
    | '/_authenticated/dev'
    | '/_authenticated/globe'
    | '/_authenticated/posts'
    | '/admin/active'
    | '/admin/ads'
    | '/admin/beta'
    | '/admin/comments'
    | '/admin/feedback'
    | '/admin/livetest'
    | '/admin/log'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/pauses'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/slangtags'
    | '/admin/stats'
    | '/admin/usernames'
    | '/admin/users'
    | '/demo/messenger'
    | '/post/$postId'
    | '/admin/'
    | '/_authenticated/channels/$channelId'
    | '/_authenticated/hashtag/$name'
    | '/_authenticated/p/$postId'
    | '/_authenticated/profile/$username'
    | '/_authenticated/slangtag/$name'
    | '/api/public/beta-launch-run'
    | '/api/public/cache-metrics'
    | '/api/public/counters-run'
    | '/api/public/moderation-run'
    | '/api/public/push-run'
    | '/api/public/retention-run'
    | '/_authenticated/channels/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AgbRoute: typeof AgbRoute
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  ImpressumRoute: typeof ImpressumRoute
  RequestDataRoute: typeof RequestDataRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RichtlinienRoute: typeof RichtlinienRoute
  ShareTargetRoute: typeof ShareTargetRoute
  DemoMessengerRoute: typeof DemoMessengerRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ApiPublicBetaLaunchRunRoute: typeof ApiPublicBetaLaunchRunRoute
  ApiPublicCacheMetricsRoute: typeof ApiPublicCacheMetricsRoute
  ApiPublicCountersRunRoute: typeof ApiPublicCountersRunRoute
  ApiPublicModerationRunRoute: typeof ApiPublicModerationRunRoute
  ApiPublicPushRunRoute: typeof ApiPublicPushRunRoute
  ApiPublicRetentionRunRoute: typeof ApiPublicRetentionRunRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-target': {
      id: '/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof ShareTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richtlinien': {
      id: '/richtlinien'
      path: '/richtlinien'
      fullPath: '/richtlinien'
      preLoaderRoute: typeof RichtlinienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-data': {
      id: '/request-data'
      path: '/request-data'
      fullPath: '/request-data'
      preLoaderRoute: typeof RequestDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/messenger': {
      id: '/demo/messenger'
      path: '/demo/messenger'
      fullPath: '/demo/messenger'
      preLoaderRoute: typeof DemoMessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usernames': {
      id: '/admin/usernames'
      path: '/usernames'
      fullPath: '/admin/usernames'
      preLoaderRoute: typeof AdminUsernamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slangtags': {
      id: '/admin/slangtags'
      path: '/slangtags'
      fullPath: '/admin/slangtags'
      preLoaderRoute: typeof AdminSlangtagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pauses': {
      id: '/admin/pauses'
      path: '/pauses'
      fullPath: '/admin/pauses'
      preLoaderRoute: typeof AdminPausesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/livetest': {
      id: '/admin/livetest'
      path: '/livetest'
      fullPath: '/admin/livetest'
      preLoaderRoute: typeof AdminLivetestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beta': {
      id: '/admin/beta'
      path: '/beta'
      fullPath: '/admin/beta'
      preLoaderRoute: typeof AdminBetaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/active': {
      id: '/admin/active'
      path: '/active'
      fullPath: '/admin/active'
      preLoaderRoute: typeof AdminActiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/globe': {
      id: '/_authenticated/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof AuthenticatedGlobeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/retention-run': {
      id: '/api/public/retention-run'
      path: '/api/public/retention-run'
      fullPath: '/api/public/retention-run'
      preLoaderRoute: typeof ApiPublicRetentionRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-run': {
      id: '/api/public/push-run'
      path: '/api/public/push-run'
      fullPath: '/api/public/push-run'
      preLoaderRoute: typeof ApiPublicPushRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moderation-run': {
      id: '/api/public/moderation-run'
      path: '/api/public/moderation-run'
      fullPath: '/api/public/moderation-run'
      preLoaderRoute: typeof ApiPublicModerationRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/counters-run': {
      id: '/api/public/counters-run'
      path: '/api/public/counters-run'
      fullPath: '/api/public/counters-run'
      preLoaderRoute: typeof ApiPublicCountersRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cache-metrics': {
      id: '/api/public/cache-metrics'
      path: '/api/public/cache-metrics'
      fullPath: '/api/public/cache-metrics'
      preLoaderRoute: typeof ApiPublicCacheMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beta-launch-run': {
      id: '/api/public/beta-launch-run'
      path: '/api/public/beta-launch-run'
      fullPath: '/api/public/beta-launch-run'
      preLoaderRoute: typeof ApiPublicBetaLaunchRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/slangtag/$name': {
      id: '/_authenticated/slangtag/$name'
      path: '/slangtag/$name'
      fullPath: '/slangtag/$name'
      preLoaderRoute: typeof AuthenticatedSlangtagNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$postId': {
      id: '/_authenticated/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof AuthenticatedPPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hashtag/$name': {
      id: '/_authenticated/hashtag/$name'
      path: '/hashtag/$name'
      fullPath: '/hashtag/$name'
      preLoaderRoute: typeof AuthenticatedHashtagNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels/$channelId': {
      id: '/_authenticated/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof AuthenticatedChannelsChannelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRoute
  AuthenticatedDevRoute: typeof AuthenticatedDevRoute
  AuthenticatedGlobeRoute: typeof AuthenticatedGlobeRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
  AuthenticatedChannelsChannelIdRoute: typeof AuthenticatedChannelsChannelIdRoute
  AuthenticatedHashtagNameRoute: typeof AuthenticatedHashtagNameRoute
  AuthenticatedPPostIdRoute: typeof AuthenticatedPPostIdRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedSlangtagNameRoute: typeof AuthenticatedSlangtagNameRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRoute,
  AuthenticatedDevRoute: AuthenticatedDevRoute,
  AuthenticatedGlobeRoute: AuthenticatedGlobeRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
  AuthenticatedChannelsChannelIdRoute: AuthenticatedChannelsChannelIdRoute,
  AuthenticatedHashtagNameRoute: AuthenticatedHashtagNameRoute,
  AuthenticatedPPostIdRoute: AuthenticatedPPostIdRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedSlangtagNameRoute: AuthenticatedSlangtagNameRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminActiveRoute: typeof AdminActiveRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminBetaRoute: typeof AdminBetaRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminLivetestRoute: typeof AdminLivetestRoute
  AdminLogRoute: typeof AdminLogRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPausesRoute: typeof AdminPausesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSlangtagsRoute: typeof AdminSlangtagsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsernamesRoute: typeof AdminUsernamesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActiveRoute: AdminActiveRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminBetaRoute: AdminBetaRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminLivetestRoute: AdminLivetestRoute,
  AdminLogRoute: AdminLogRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPausesRoute: AdminPausesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSlangtagsRoute: AdminSlangtagsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsernamesRoute: AdminUsernamesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AgbRoute: AgbRoute,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  ImpressumRoute: ImpressumRoute,
  RequestDataRoute: RequestDataRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RichtlinienRoute: RichtlinienRoute,
  ShareTargetRoute: ShareTargetRoute,
  DemoMessengerRoute: DemoMessengerRoute,
  PostPostIdRoute: PostPostIdRoute,
  ApiPublicBetaLaunchRunRoute: ApiPublicBetaLaunchRunRoute,
  ApiPublicCacheMetricsRoute: ApiPublicCacheMetricsRoute,
  ApiPublicCountersRunRoute: ApiPublicCountersRunRoute,
  ApiPublicModerationRunRoute: ApiPublicModerationRunRoute,
  ApiPublicPushRunRoute: ApiPublicPushRunRoute,
  ApiPublicRetentionRunRoute: ApiPublicRetentionRunRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
